name: "Build and Test"

on: 
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

  workflow_dispatch:

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: SwiftLint rules violations with --strict
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict

  # build_test:
  #   name: Run tests
  #   runs-on: macos-latest
  
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3.3.0

  #     - name: Cancel Previous Runs
  #       uses: styfle/cancel-workflow-action@0.11.0
  #       with:
  #         access_token: ${{ github.token }}

  #     - uses: maxim-lobanov/setup-xcode@v1.5.1
  #       with:
  #         xcode-version: latest-stable

  #     - uses: ruby/setup-ruby@v1.137.2

  #     - name: Install Bundler
  #       run: gem install bundler

  #     - name: Install gems
  #       run: bundle install

  #     - name: Cocoapods Cache
  #       uses: actions/cache@v3.2.5
  #       id: cocoapods-cache
  #       with:
  #         path: Pods
  #         key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-pods-

  #     - name: Swift Packages Cache
  #       uses: actions/cache@v3.2.5
  #       id: cache
  #       with:
  #         path: |
  #           Build/SourcePackages
  #           Build/Build/Products
  #         key: ${{ runner.os }}-deps-v1-${{ hashFiles('BILDsolid.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
  #         restore-keys: ${{ runner.os }}-deps-v1-

  #     - name: CocoaPods
  #       if: steps.cocoapods-cache.outputs.cache-hit != 'true'
  #       run: |
  #         pod install

  #     - name: Run Tests (No Cache)
  #       if: steps.setup.outputs.cache-hit != 'true'
  #       run: bundle exec fastlane unit_tests

  #     - name: Run Tests (Cache)
  #       if: steps.setup.outputs.cache-hit == 'true'
  #       run: bundle exec fastlane unit_tests skip_package_dependencies_resolution:true

